server:
  port: 8080

camel:
  component:
    servlet:
      mapping:
        context-path: /*
  springboot:
    main-run-controller: true
    json-validator:
      basic-property-binding: false
logging:
  level:
    root: INFO
    org.springframework.web: INFO

backend:
  orderservice.url: http://localhost:8080